version: 2
updates:
- package-ecosystem: composer
  directory: "/api"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bref/bref
    versions:
    - 1.2.0
    - 1.2.1
    - 1.2.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.76
    - 0.12.78
  - dependency-name: vlucas/phpdotenv
    versions:
    - 5.3.0
