version: "3.5"

services:
  app:
    build:
      context: ./api
    ports:
      - '8181:8181'
    volumes:
      - ./api:/var/www
    environment:
      DEBUG: $DEBUG
      CLIENT_ID: $CLIENT_ID
      SECRET: $SECRET
      REDIRECT_URL: $REDIRECT_URL
      STATE: $STATE
      GITLAB_URL: $GITLAB_URL
      WEBHOOK_INCOME_URL: $WEBHOOK_INCOME_URL
      WEBHOOK_TOKEN: $WEBHOOK_TOKEN
      WEBHOOK_PUSH: $WEBHOOK_PUSH
      WEBHOOK_ENABLE_SSL_VERIFICATION: $WEBHOOK_ENABLE_SSL_VERIFICATION
