name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Validate composer.json and composer.lock
      run: composer validate -d api/

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install -d api/ --dev --prefer-dist --no-progress --no-suggest

    - name: Run unit test suite
      run: composer run -d api/ test:unit

    - name: Run integration test suite
      run: composer run -d api/ test:integration

    - name: Run e2e test suite
      run: composer run -d api/ test:e2e
